//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrotAPI_Final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class like_comentario
    {
        public int id_like_comentario { get; set; }
        public int id_user { get; set; }
        public int id_comentario { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    
        public virtual comentarios comentarios { get; set; }
        public virtual users users { get; set; }
    }
}
