//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrotAPI_Final.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBContextModel : DbContext
    {
        public DBContextModel()
            : base("name=BorrarDBBrotEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<categoria> categoria { get; set; }
        public virtual DbSet<comentarios> comentarios { get; set; }
        public virtual DbSet<interaccion_post> interaccion_post { get; set; }
        public virtual DbSet<like_comentario> like_comentario { get; set; }
        public virtual DbSet<like_post> like_post { get; set; }
        public virtual DbSet<publicacion_guardada> publicacion_guardada { get; set; }
        public virtual DbSet<publicaciones> publicaciones { get; set; }
        public virtual DbSet<seguidores> seguidores { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<usuario_categoria> usuario_categoria { get; set; }
        public virtual DbSet<visita_busqueda> visita_busqueda { get; set; }
        public virtual DbSet<visita_pefil_post> visita_pefil_post { get; set; }
    }
}
