//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrotAPI_Final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class seguidores
    {
        public int id_seguidores { get; set; }
        public int seguidor_id { get; set; }
        public int id_seguido { get; set; }
        public Nullable<bool> accepted { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    
        public virtual users users { get; set; }
        public virtual users users1 { get; set; }
    }
}
